services:
  node:
    image: node:16
    container_name: node-app
    working_dir: /usr/src/app
    volumes:
      - ./back:/usr/src/app
    ports:
      - 3000:3000
    command: npm install
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - mysql

  nuxt:
    image: node:16
    container_name: nuxt-app
    working_dir: /usr/src/app
    volumes:
      - ./front:/usr/src/app
    ports:
      - 3001:3000
    command: npm run dev
    depends_on:
      - node

volumes:
  mysql-data:
