services:
  node:
    image: node:18
    container_name: node-app
    working_dir: /usr/src/app
    volumes:
      - ./back:/usr/src/app
    ports:
      - 27890:3000
      - 27891:3001
    command: sh -c "npm install && npx nodemon main.js"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - back/.env
    environment:
      - MYSQL_DATABASE=DEFCON1  
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - mysql

volumes:
  mysql-data:
