services:
  node:
    image: nikolaik/python-nodejs
    container_name: node
    env_file:
      - back/.env
    working_dir: /usr/src/app
    volumes:
      - ./back:/usr/src/app
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 3003:3003
    command: sh -c "npm install && pip install -r ./microserveis/python/requirements.txt && npx nodemon main.js"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - back/.env
    environment:
      - MYSQL_DATABASE=a23alechasan_defcon1 
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - mysql

  vuetify:
    image: node:18
    container_name: vuetify
    working_dir: /usr/src/app
    volumes:
      - ./front/vuetify-project:/usr/src/app
    ports:
      - 4000:3000
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - node  

volumes:
  mysql-data:
